### ISSUE TITLE
Running in Scala causes cross compile errors

### ISSUE THREAD

**Issue by wsargent** [opentracing-contrib/java-kafka-client#6]
The java-kafka-client in release 0.0.1 is tied to the Scala 2.11 version of Kafka, and there is no Scala 2.12 version available:

```
[error]    org.scala-lang.modules:scala-parser-combinators _2.12, _2.11
java.lang.RuntimeException: Conflicting cross-version suffixes in: org.scala-lang.modules:scala-parser-combinators
	at scala.sys.package$.error(package.scala:27)
```

In the master branch, it's tied to 2.12 exclusively:

https://github.com/opentracing-contrib/java-kafka-client/blob/master/pom.xml#L58

It might be nice to have a Scala project with Java and Scala APIs that could use SBT cross compile logic for producing both versions.

**Comment by malafeev** [comment]
version `0.0.2` uses 2.12 (should be available in maven central in couple of hours).

is it needed support for 2.11? For that case we can create maven multi module project to build 2 packages for 2.11 and 2.12. But I'm not sure that somebody interested in 2.11

**Comment by agolomoodysaada** [comment]
Some Spark cloud offerings are stuck with Scala 2.11 and we cannot rebuild them. We're interested in 2.11 support.

**Comment by agolomoodysaada** [comment]
Here's a sample migration from maven to sbt https://github.com/jaytaylor/goose-ng/commit/496adef0a635216874ac95438d606ce66eaadddc

**Comment by malafeev** [comment]
fixed in 0.0.8

**Comment by wsargent** [comment]
@malafeev is there something up with Maven?  https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-kafka-client shows 0.0.7 still...

**Comment by malafeev** [comment]
it takes time :)
0.0.8 is available now

**Comment by wsargent** [comment]
This is still a problem for me, because 0.0.8 depends on opentracing 0.31.0, and the codebase I have is running on 0.30.0 and realistically isn't going to move to 0.31.0 for several months.

**Comment by malafeev** [comment]
for that case https://github.com/opentracing/opentracing-java-v030/ was created.
could you try it?

**Comment by wsargent** [comment]
Also 0.0.8 depends on org.apache.kafka:kafka-clients:1.0.0 which is a leap
